import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
  <nav className="fixed top-0 left-0 w-full z-50 bg-gradient-to-r from-cyan-900/80 via-slate-900/80 to-emerald-900/80 shadow-lg backdrop-blur">
          <div className="container mx-auto flex justify-center items-center px-6 py-4">
            <div className="flex gap-8 text-lg font-bold tracking-wide text-white drop-shadow-md">
              <Link href="/#about" className="transition-colors duration-200 hover:bg-gradient-to-r hover:from-cyan-400 hover:to-emerald-400 hover:bg-clip-text hover:text-transparent">About</Link>
              <Link href="/#skills" className="transition-colors duration-200 hover:bg-gradient-to-r hover:from-cyan-400 hover:to-emerald-400 hover:bg-clip-text hover:text-transparent">Skills</Link>
              <Link href="/#projects" className="transition-colors duration-200 hover:bg-gradient-to-r hover:from-cyan-400 hover:to-emerald-400 hover:bg-clip-text hover:text-transparent">Projects</Link>
              <a
                href="/Jeff_Owusu_final.pdf"
                target="_blank"
                rel="noopener noreferrer"
                className="transition-colors duration-200 hover:bg-gradient-to-r hover:from-cyan-400 hover:to-emerald-400 hover:bg-clip-text hover:text-transparent"
              >
                Resume
              </a>
              <Link href="/#contact" className="transition-colors duration-200 hover:bg-gradient-to-r hover:from-cyan-400 hover:to-emerald-400 hover:bg-clip-text hover:text-transparent">Contact</Link>
            </div>
          </div>
        </nav>
        <div className="pt-16">{children}</div>
      </body>
    </html>
  );
}
